/*
 * This file is part of the DiffX library.
 *
 * For licensing information please see the file license.txt included in the release.
 * A copy of this licence can also be found at 
 *   http://www.opensource.org/licenses/artistic-license-2.0.php
 */
package com.topologi.diffx.format;

import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;

import junit.framework.AssertionFailedError;

import org.junit.Before;
import org.junit.Test;
import org.xml.sax.InputSource;

import com.topologi.diffx.DiffXException;
import com.topologi.diffx.event.impl.AttributeEventNSImpl;
import com.topologi.diffx.event.impl.CloseElementEventNSImpl;
import com.topologi.diffx.event.impl.OpenElementEventNSImpl;
import com.topologi.diffx.load.SAXRecorder;
import com.topologi.diffx.sequence.EventSequence;
import com.topologi.diffx.util.Constants;

/**
 * Test class for the strict formatter. 
 * 
 * @author Christophe Lauret
 * @version 16 December 2004  
 */
public final class StrictXMLFormatterTest {

  /**
   * The namespace declaration.
   */
  private static final String XML_DECL = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n";

  /**
   * The namespace declaration.
   */
  private static final String NS_DECL = "xmlns:dfx=\""+Constants.BASE_NS_URI+'"';

  /**
   * The loader being tested.  
   */
  private SAXRecorder recorder = new SAXRecorder();

  /**
   * The formatter being tested.  
   */
  private XMLDiffXFormatter formatter = null;

  /**
   * The string writer.  
   */
  private StringWriter w = null;

  /**
   * @see junit.framework.TestCase#setUp()
   */
  @Before public void setUp() throws Exception {
    this.w = new StringWriter();
    this.formatter = new StrictXMLFormatter(this.w);
  }

//opening and closing elements ---------------------------------------------------------------

  /**
   * Test open and closing an element.
   * 
   * @throws DiffXException Should an error occur whilst parsing one of the XML files. 
   * @throws IOException    Should an I/O error occur.
   */
  @Test public void testOpenAndClose0() throws DiffXException, IOException {
    this.formatter.format(new OpenElementEventNSImpl("a"));
    this.formatter.format(new CloseElementEventNSImpl("a"));
    assertEquivalentToXML("<a/>");
    String xml = XML_DECL+"<a "+NS_DECL+"></a>";
    assertEquals(xml, this.w.toString());
  }

// playing with attributes --------------------------------------------------------------------

  /**
   * Test formatting an attribute.
   * 
   * @throws DiffXException Should an error occur whilst parsing one of the XML files. 
   * @throws IOException    Should an I/O error occur.
   */
  @Test public void testAttributes0() throws DiffXException, IOException {
    this.formatter.format(new OpenElementEventNSImpl("a"));
    this.formatter.format(new AttributeEventNSImpl("x", "", "y"));
    this.formatter.format(new CloseElementEventNSImpl("a"));
    assertEquivalentToXML("<a x='y'/>");
    String xml = XML_DECL+"<a "+NS_DECL+" x=\"y\"></a>";
    assertEquals(xml, this.w.toString());
  }

// helpers ------------------------------------------------------------------------------------

  /**
   * Tests whether the content generated by the formatter is equivalent to the specified XML. 
   * 
   * @param xml The first XML to test.
   * 
   * @throws DiffXException Should an error occur whilst parsing one of the XML files. 
   * @throws IOException    Should an I/O error occur.
   */
  private void assertEquivalentToXML(String xml) throws DiffXException, IOException {
    // process the XML to get the sequence
    Reader xmlr = new StringReader(xml);
    EventSequence exp = this.recorder.process(new InputSource(xmlr));
    // process the output of the formatter
    Reader xmlr2 = new StringReader(this.w.toString());
    EventSequence seq = this.recorder.process(new InputSource(xmlr2));
    try {
      assertEquals(exp.size(), seq.size());
      assertEquals(exp, seq);
    } catch (AssertionFailedError ex) {
      PrintWriter pw = new PrintWriter(System.err);
      seq.export(pw);
      pw.flush();
      throw ex;
    }
    System.err.println(this.w.toString());
  }

}

