/*
 * This file is part of the DiffX library.
 *
 * For licensing information please see the file license.txt included in the release.
 * A copy of this licence can also be found at 
 *   http://www.opensource.org/licenses/artistic-license-2.0.php
 */
package com.topologi.diffx.test;

import java.io.File;

/**
 * A testing utility class.
 * 
 * @author Christophe Lauret (Weborganic)
 * @version 28 March 2010
 */
public class TestUtils {

  /**
   * Utility class.
   */
  private TestUtils() {
  }

  /**
   * Returns the data directory for the class being tested.
   * 
   * <p>The data directory contains test data that is permanent and required for performing tests
   * (eg. source data, etc...)
   * 
   * @param c The class being tested.
   * @return the corresponding data directory.
   */
  public static File getDataDirectory(Class<?> c) {
    File data = new File("data");
    String dir = c.getName().replace('.', File.separatorChar);
    return new File(data, dir);
  }

  /**
   * Returns the temporary directory for the class being tested.
   * 
   * <p>The temporary directory contains test data that is generated by the test from data can be deleted
   * (eg. generated index, etc...)
   * 
   * @param c The class being tested.
   * @return the corresponding data directory.
   */
  public static File getTempDirectory(Class<?> c) {
    File data = new File("tmp");
    String dir = c.getName().replace('.', File.separatorChar);
    return new File(data, dir);
  }

}
